5.2 django allauth
thinknetica-django-lab-01/Smith-84 pull request #46
Opened 2021-02-07 10:48 UTC by Smith-84

Closes #36

2021-02-08 09:38 UTC, morgangt requested changes

2021-02-08 09:38 UTC, morgangt commented on rental_site/rental_site/settings.py
>  ALLOWED_HOSTS = []
Надо добавить какие нибудь домены, если доменов будет много то то можно использовать * если подсменной будет много то модно использовать *.your-domain.com
Но лучше такие вещи выносить в конфиги

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/views.py
> +    form_class_sets = {
В словаре ключи написаны кириллицей, это допустимо но лучше так не делать, принято использовать ключи в словаре написаные латинскими буквами

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/choice_type.html
> +    <div class="custom-tab style-1">
Список можно сгененрить автоматически, например на back-end сформировать словарь или список а здесь этот список выводить  в цикле, предлагаю рассмотреть эту идею, например в следующем pull-request, так можно будет сделать этот список расширяемым а в будущем записывать список, типов объявлений, в БД

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/components/header.html
> +                        {% else %}
авторизованный пользователь не может добавить объявление ?

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/dashboard.html
> +											<p class="mb-0">© 2021 Develop By <a href="#">Stepanov Vladimir</a> All Rights Reserved</p>
Предлогам сделать текущий код вычисляемым

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/form.html
> +                    {{ form|crispy  }}
Две формы подряд, может стоит как-то отделить одну форму от другой, например заголовком h3

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/form.html
> +                        <button class="btn btn-theme bg-2" type="submit">Save Changes</button>
Странно что сайт по больше степени на русском а кнопка сохранить изменения на английском, давайте сделаем все на русском

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/templates/form_files.html
> +                    {{ form|crispy  }}
Тут тоже две формы подряд не чем не отделены даже тегом hr

2021-02-08 09:38 UTC, morgangt commented on rental_site/main/views.py
> +            messages.error(request, 'Ошибка!')
Давайте сделаем чуть более информативную ошибку сделаем, например возьмём текст ошибки с валидация формы

2021-02-08 14:43 UTC, Smith-84 commented on rental_site/rental_site/settings.py
>  ALLOWED_HOSTS = []
я выпилил этот функционал

2021-02-08 14:45 UTC, Smith-84 commented on rental_site/main/templates/form_files.html
> +                    {{ form|crispy  }}
Зачем? смыслового разграничения не требуется...полшьзователь представляет это как едину форму добавления объявления

2021-02-08 14:47 UTC, Smith-84 commented on rental_site/main/templates/components/header.html
> +                        {% else %}
Нет не видит..видит ссылку на свой лк...вопросы в области ux/ui

2021-02-09 10:28 UTC, Smith-84 commented on rental_site/main/templates/choice_type.html
> +    <div class="custom-tab style-1">
Мне не совсем понятно для чего? Потому что просится итерация по списку?
урлы шаблонов в моем понимании относятся к  темпалейтам а не к вью...искуственно создавать структуру по которой нужно итерироватся?...писать в базу?
то есть есть: в файле урлс.пай в котором инициальзируются названия темплейтов потом мы эти названия записываем в базу с названием таблиц и соответсвием, потом получаем запросом их из базы и выдаем в контекст?
url.py - models -view - template ?
"правой ногой почесать левое ухо"
какое ваше мнение?

2021-02-09 10:44 UTC, morgangt approved these changes

2021-02-09 10:44 UTC, morgangt commented on rental_site/main/templates/components/header.html
> +                        {% else %}
Возможно авторизованному пользователю тоже дать возможность добавлять объявления на этой странице?

2021-02-09 10:44 UTC, morgangt commented on rental_site/main/templates/choice_type.html
> +    <div class="custom-tab style-1">
хорошо, если ваше "т.з не предполагает существенного увелечения списка типов недвижимости" то можно оставить в таком виде. тем более вам в таком случае и urls.py придется переделать.

2021-02-09 11:30 UTC, Smith-84 commented on rental_site/main/templates/components/header.html
> +                        {% else %}
Хорошо

2021-02-09 11:32 UTC, Smith-84 commented on rental_site/main/templates/choice_type.html
> +    <div class="custom-tab style-1">
Отлично спасибо

2021-02-09 11:33 UTC, merged