9.3 docstring
thinknetica-django-lab-01/Smith-84 pull request #86
Opened 2021-02-22 20:25 UTC by Smith-84

Closes #69

2021-02-23 10:04 UTC, mikhailborodin requested changes

2021-02-23 10:04 UTC, mikhailborodin commented on docs/_build/html/index.html
> +
всё, что билдится, надо добавить в .gitignore

2021-02-23 10:50 UTC, Smith-84 commented on docs/_build/html/index.html
> +
Удалил _build

2021-02-24 09:48 UTC, mikhailborodin approved these changes

2021-02-24 11:49 UTC, merged