Closes #8
thinknetica-django-lab-01/Smith-84 pull request #9
Opened 2021-01-19 13:09 UTC by Smith-84

Done

2021-01-19 13:21 UTC, vkurennov commented
@Smith-84 Чтобы PR связался с issues, надо не в заголовке написать Closes #8, а в описании. Там, где сейчас Done написано. Можно просто отредактировать описание.

2021-01-20 03:26 UTC, mikhailborodin requested changes

2021-01-20 03:26 UTC, mikhailborodin commented on rental_site/rental_site/settings.py
> +    'django.contrib.staticfiles',
приложение main должно быть добавлено в `INSALLED_APPS`

2021-01-20 08:20 UTC, Smith-84 commented on rental_site/rental_site/settings.py
> +    'django.contrib.staticfiles',
Fix

2021-01-20 14:15 UTC, mikhailborodin approved these changes

2021-01-20 14:47 UTC, merged